[package]
name = "kobold"
version = "0.1.0"
authors = ["Postrex <post-rex@pm.me>"]
edition = "2018"

[dependencies]
actix-web = "3.1.0                                  "

[dev-dependencies]
cargo-about = "0.2"
env_logger = "0.7"
